services:
  mongodb:
    image: mongo:6.0  # 使用 MongoDB 6.0 版本镜像
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root  # 设置 root 用户名
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword  # 设置 root 密码
    ports:
      - "27017:27017"  # 映射端口：主机的 27017 端口映射到容器的 27017
    volumes:
      - ./data/mongo:/data/db  # 数据持久化到本地的 data/mongo 文件夹
    networks:
      - mongodb-network
    restart: always

networks:
  mongodb-network:
    driver: bridge

volumes:
  mongo-data:

